version: "3.8"

services: 
    # backend 
    smart-brain-api:
        container_name: backend
        build: ./
        command: npm start
        working_dir: /usr/src/smart-brain-api
        ports: 
            - "3500:3500"
        volumes: 
            - ./:/usr/src/smart-brain-api
        links: 
            - postgres
            - redis
        environment: 
            POSTGRES_URI: postgresql://sam:secret@postgres:5432/smart-brain-docker
            REDIS_URI: redis://redis:6379

    # postgres database
    postgres:
        build: ./postgres
        ports:
            - "5432:5432"
        environment: 
            POSTGRES_USER: sam 
            POSTGRES_PASSWORD: secret
            POSTGRES_DB: smart-brain-docker

    # redis database
    redis:
        image: redis
        ports: 
            - "6379:6379"
            
    